name: 'Github Actions testing'

on:
  push:
    branches:
    - main
  pull_request:
  pull_request_target:
    branches:
    - main
  workflow_dispatch:

jobs:
  debug-ssh:
    name: 'Debug via SSH'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # Intentionally vulnerable
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Hello World
      run: echo ${{secrets.GITHUB_TOKEN}}

    - name: Run script
      run: |
        chmod +x example.sh
        ./example.sh
      
    # - name: Debugging with ssh
    #   uses: lhotari/action-upterm@v1
    #   with:
    #     limit-access-to-actor: true
